### ISSUE TITLE
Dependency for planning tasks

### ISSUE THREAD

**Issue by muzhancun** [buoyancy99/diffusion-forcing#1]
In the `extra-requirements.txt`, dm-control 1.0.20 requires mujoco>=3.1.6. However d4rl requires mujoco-py, which does not support mujoco>=3.1.6

**Comment by buoyancy99** [comment]
Hello, dm-control 1.0.20 sounds like a really high version for this d4rl. Since the only dependency related to it is `dm_control>=1.0.3` in d4rl repo, could you downgrade it to this minimal version? For mujoco, you shall use mujoco 210 as suggested in the README

**Comment by muzhancun** [comment]
> Hello, dm-control 1.0.20 sounds like a really high version for this d4rl. Since the only dependency related to it is `dm_control>=1.0.3` in d4rl repo, could you downgrade it to this minimal version? For mujoco, you shall use mujoco 210 as suggested in the README

Thanks! Looking forward to your transformer implementation for planning

**Comment by buoyancy99** [comment]
Hi, I just released the transformer version on main branch!
