### ISSUE TITLE
datasets of robot imitation learning

### ISSUE THREAD

**Issue by hiterlly** [buoyancy99/diffusion-forcing#14]
Hello，

Can you provide the datasets of robot imitation learning?

Thanks

**Comment by buoyancy99** [comment]
Yes, I will look into this

**Comment by buoyancy99** [comment]
I just uploaded it to [google drive](https://drive.google.com/file/d/1snsPpeGeYERgLXB0LYJb5lV1VwnOWNQg/view?usp=sharing)
