### ISSUE TITLE
Clarification on the Understanding of ee_pos and ee_pos_target

### ISSUE THREAD

**Issue by le-wei** [buoyancy99/diffusion-forcing#17]
Thank you very much for the work you have done. I have a question regarding the robot_swap dataset that I need your help with. Can we understand ee_pos and ee_pos_target in this way: at time t, the ee_pos is A, and ee_pos_target is B. If the robot can definitely reach the target position, then at time t+1, the ee_pos should be B. When recording the data, can ee_pos and ee_pos_target be understood as the current state and action of the robot, respectively? Is this correct? I greatly appreciate your response.

**Comment by buoyancy99** [comment]
Yes
