### ISSUE TITLE
About the Causality of the Diffusion Planning

### ISSUE THREAD

**Issue by hw-du** [buoyancy99/diffusion-forcing#19]
Hi! May I have another question about the causality of the diffusion planning? In the paper it says Diffusion Forcing trains causal sequence neural networks, but why in df_planning.yaml, the parameter causal: False is set as False? Thank you!

**Comment by buoyancy99** [comment]
The latest code (v1.5) slightly differs from v1.

Diffusion Forcing (the first paper) is about causal diffusion forcing only. However, as we move further into the later stage of the project, we realized that diffusion forcing's fractional masking can interpolate between causal and non-causal as well. Consider the scenario that we use non-causal attention - we can still implement causality by controlling noise. By labeling the future as full white noise, there is no information leaked into the past tokens. By labeling future tokens as free of noise it's completely non-causal. By labeling future as almost white noise, a slight amount of information is leaked to past tokens. This effectively states that one only need a non-causal architecture, but controlling fractional noise of the future, to achieve causality. Therefore we release that version of code in v1.5 directly.

**Comment by hw-du** [comment]
Thank you!
