### ISSUE TITLE
Diffusion policy code for robot imitation learning

### ISSUE THREAD

**Issue by talha1503** [buoyancy99/diffusion-forcing#25]
Hi, I was trying to reproduce the code for robot_swap environment. In the paper, you mention comparison with diffusion policy. Do you also have the code to make diffusion policy work with the robot_swap environment?

**Comment by buoyancy99** [comment]
Unfortunately, I'd like to keep that part of my toolkit code base private for now. 

However, you shall easily modify this code base to train a diffusion policy (e.g. as a two-token sequence with some entries padded) by subclassing df_robot, and leverage the same robot interface

**Comment by talha1503** [comment]
Got it! Thanks a lot

**Comment by buoyancy99** [comment]
BTW if you modify this code base to train diffusion policy, don't forget to add random crop augmentation to image which is really important to reproducing diffusion policy

**Comment by talha1503** [comment]
Thanks for the heads up! I will keep this in mind :D
