### ISSUE TITLE
Why diffusion forcing won't blow up?

### ISSUE THREAD

**Issue by xizaoqu** [buoyancy99/diffusion-forcing#28]
Thanks for your interesting work. I've checked the code and found that in the temporal attention implementation, each time the newest noisy frame will condition on previous almost clean frames for denoising. I'm wondering why in this case the auto-regressively generated frames will not face quality degradation. Could you provide some insights about this? Thanks.

**Comment by xizaoqu** [comment]
BTW, I found in GameNGen (https://gamengen.github.io/) it reports that using noise augmentation can mitigate auto-regressive drift.

**Comment by Johanan528** [comment]
I have the same question. In fact, our recent [work](https://arxiv.org/abs/2412.03568) only used a single predicted clean frame as a condition, and we found that the degradation issue indeed exists. However, our subsequent experiments found that using a multi-frame noisy version as the condition works much better. Combining the performance of diffusion forcing, I guess whether using multiple frames as conditions could alleviate the drift.

**Comment by buoyancy99** [comment]
I explained this in our talk video https://www.youtube.com/watch?v=CNgwS8B7UvE
