### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JC-LMCO** [buoyancy99/diffusion-forcing#3]
I'm interested in using this work on some of my own video-diffusion data (the MC guidance and causal uncertainty parts seems like it'd be a very good fit). What license is your code released under?

**Comment by buoyancy99** [comment]
Hi, I just added an MIT license. Thank you for your interest. Please also checkout our 3D Unet code base since that works better for video diffusion

**Comment by JC-LMCO** [comment]
Thank you, I will check that out as well!
