### ISSUE TITLE
Out-of-Memory when running on a100 gpu

### ISSUE THREAD

**Issue by guyuchao** [buoyancy99/diffusion-forcing#31]
Hi, I start training with following command "python -m main +name=train_try1 algorithm=df_video dataset=video_minecraft" but encounter oom problem. My running gpu is 4 x A100 40g, and use your default cfg. I wonder how much resource required to run this training.

<img width="1097" alt="Screenshot 2024-12-16 at 11 33 27" src="https://github.com/user-attachments/assets/bd88634e-a0e6-4250-a576-c03171999bff" />

**Comment by guyuchao** [comment]
The input x shape for unet 3d is: torch.Size([8, 3, 10, 128, 128]).

**Comment by buoyancy99** [comment]
Notice our batch size 8 is per GPU, so feel free to tune down the batch size. Diffusion Forcing 2 is more memory efficient as it's a latent diffusion model and it will come out late Jan.

**Comment by guyuchao** [comment]
Do you use the A100 80GB GPU in your experiment with a batch size of 8 per GPU?

**Comment by buoyancy99** [comment]
I believe so, every value in the README is default value when I used to train them
