### ISSUE TITLE
 The Naming Inspiration Behind "Diffusion Forcing" Architecture

### ISSUE THREAD

**Issue by Perkins729** [buoyancy99/diffusion-forcing#4]
Hello,

I am curious about the rationale behind the naming of your architecture as "Diffusion Forcing". Could you please share the inspiration and thought process that led to this choice of name?

Thank you for your time and insights.

**Comment by gunnxx** [comment]
I believe it is a combination between **Diffusion** Model and Teacher **Forcing** as they try to do something in between. It is on their [project website](https://boyuan.space/diffusion-forcing/).

**Comment by buoyancy99** [comment]
The naming is modified from **Teacher Forcing** by replacing Teacher with Diffusion as other users mentioned above.

The elegance that leads to this name: As mentioned in the paper, we found that the input-output behavior of a learned bayes filter under noise is the same as the input-output behavior of diffusion. Therefore I looked for a name that organically combines the two.
