### ISSUE TITLE
Output Action Contains NaN in Diffusion Forcing Planning

### ISSUE THREAD

**Issue by devinluo27** [buoyancy99/diffusion-forcing#5]
I trained diffusion forcing on Maze2d following the command in README. When I do the planning using the trained model, the output actions are 'NaN' occasionally, which compromises the mujoco simulation. Do you have any suggestions to resolve this issue?

**Comment by buoyancy99** [comment]
Hello, I am looking into this. Could be some non-robust behavior I accidentally created when cleaning up the code

**Comment by buoyancy99** [comment]
Sorry about the issue, this is confirmed to be a bug when cleaning up the code. I will push the fix among a much improved version with my new transformer implementation of df_planning next week, with much better results and much faster speed!

**Comment by devinluo27** [comment]
Thank you for the update! I will check out the updated version once it's published.

**Comment by buoyancy99** [comment]
It seems I need more time to release a nice and clean repo for the transformer version of planning. However, I fixed this problem for now in #2, just follow the instructions in it and try my ckpt!

**Comment by buoyancy99** [comment]
I just released the transformer version on main branch. Check it out and here are some visualizations of it!

![Screenshot 2024-07-30 at 6 38 36 PM](https://github.com/user-attachments/assets/3dd4939b-f056-40d6-90ee-9803993064dd)
