### ISSUE TITLE
Time-Series Visualization Process for Different Datasets using Diffusion Forcing

### ISSUE THREAD

**Issue by alanwang8** [buoyancy99/diffusion-forcing#7]
Hello,

I currently want to use diffusion forcing for my own time-series dataset, particularly to analyze multiple time-series signals simultaneously, similar to the multivariate forecasting you mentioned in your paper.

**How can I create visualizations to illustrate the forecasting/prediction process for diffusion forcing on time series data?**

Please let me know if you have any questions about my use case or need further clarification.

Thanks!

**Comment by diego-marti** [comment]
Hi there! You can launch a time series experiment with the command 
```
python -m main +name=ts_exchange dataset=ts_exchange algorithm=df_prediction experiment=exp_prediction
```
The time series visualizations from Fig. 6 in the paper are created automatically in the [test epoch](https://github.com/buoyancy99/diffusion-forcing/blob/main/algorithms/diffusion_forcing/df_prediction.py#L97) at the end of training. You can look into the function [`log_timeseries_plots`](https://github.com/buoyancy99/diffusion-forcing/blob/main/utils/logging_utils.py#L352) to modify the plots. Hope this helps!
